import {
  SiAngularjs,
  SiChakraui,
  SiCsharp,
  SiCss3,
  SiDotnet,
  SiGit,
  SiGithub,
  SiHtml5,
  SiIterm2,
  SiJavascript,
  SiMysql,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiReact,
  SiRedux,
  SiRuby,
  SiRubyonrails,
  SiSass,
  SiScala,
  SiSqlite,
  SiSwift,
  SiTypescript,
  SiUnity,
  SiVisualstudiocode,
  SiWordpress,
} from 'react-icons/si';
import { RxLaptop, RxMoon, RxSun } from 'react-icons/rx';

export const Icons = {
  Laptop: RxLaptop,
  Moon: RxMoon,
  Sun: RxSun,
}

export const ExpIcons = {
  Angularjs: SiAngularjs,
  Chakraui: SiChakraui,
  Csharp: SiCsharp,
  Css3: SiCss3,
  Dotnet: SiDotnet,
  Git: SiGit,
  Github: SiGithub,
  Html5: SiHtml5,
  Iterm2: SiIterm2,
  Javascript: SiJavascript,
  Mysql: SiMysql,
  Nodedotjs: SiNodedotjs,
  Php: SiPhp,
  Postgresql: SiPostgresql,
  Python: SiPython,
  React: SiReact,
  Redux: SiRedux,
  Ruby: SiRuby,
  Rubyonrails: SiRubyonrails,
  Sass: SiSass,
  Scala: SiScala,
  Sqlite: SiSqlite,
  Swift: SiSwift,
  Typescript: SiTypescript,
  Unity: SiUnity,
  Visualstudiocode: SiVisualstudiocode,
  Wordpress: SiWordpress,
}

export default Icons